export const FETCH_LOGS_DONE = "FETCH_LOGS_DONE";
export const FETCH_LOGS_PROGRESS = "FETCH_LOGS_PROGRESS";

export const PUBLISH_LOG_PROGRESS = "PUBLISH_LOG_PROGRESS";
export const PUBLISH_LOG_DONE = "PUBLISH_LOG_DONE";

export const LOG_ADDED = "LOG_ADDED";

export const EVENT_ADDED = "EVENT_ADDED";

export const FETCH_BUNDLES_DONE = "FETCH_BUNDLES_DONE";
export const FETCH_BUNDLES_PROGRESS = "FETCH_BUNDLES_PROGRESS";

export const STOP_BUNDLE = "STOP_BUNDLE";
export const START_BUNDLE = "START_BUNDLE";

export const BUNDLE_CHANGED = "BUNDLE_CHANGED";

export const SET_LOG_PREFERENCES = "SET_LOG_PREFERENCES";
export const SET_BUNDLE_PREFERENCES = "SET_BUNDLE_PREFERENCES";

export const SELECT_BUNDLE = "SELECT_BUNDLE";

export const DISMISS_BUNDLE = "DISMISS_BUNDLE";

export const OPEN_RPC_MODAL = "OPEN_RPC_MODAL";
export const CLOSE_RPC_MODAL = "CLOSE_RPC_MODAL";

export const PERFORM_RPC_PROGRESS = "PERFORM_RPC_PROGRESS";
export const PERFORM_RPC_DONE = "PERFORM_RPC_DONE";

export const FETCH_SERVICES_PROGRESS = "FETCH_SERVICES_PROGRESS";
export const FETCH_SERVICES_DONE = "FETCH_SERVIES_DONE";

export const FETCH_SUMMARY_PROGRESS = "FETCH_SUMMARY_PROGRESS";
export const FETCH_SUMMARY_DONE = "FETCH_SUMMARY_DONE";
