export const FETCH_LOGS_DONE = "FETCH_LOGS_DONE";
export const FETCH_LOGS_PROGRESS = "FETCH_LOGS_PROGRESS";

export const FETCH_BUNDLES_DONE = "FETCH_BUNDLES_DONE";
export const FETCH_BUNDLES_PROGRESS = "FETCH_BUNDLES_PROGRESS";

export const PUBLISH_LOG_PROGRESS = "PUBLISH_LOG_PROGRESS";
export const PUBLISH_LOG_DONE = "PUBLISH_LOG_DONE";
