export const FETCH_LOGS_DONE = "FETCH_LOGS_DONE";
export const FETCH_LOGS_PROGRESS = "FETCH_LOGS_PROGRESS";

export const PUBLISH_LOG_PROGRESS = "PUBLISH_LOG_PROGRESS";
export const PUBLISH_LOG_DONE = "PUBLISH_LOG_DONE";

export const LOG_ADDED = "LOG_ADDED";

export const EVENT_ADDED = "EVENT_ADDED";

export const FETCH_BUNDLES_DONE = "FETCH_BUNDLES_DONE";
export const FETCH_BUNDLES_PROGRESS = "FETCH_BUNDLES_PROGRESS";

export const STOP_BUNDLE = "STOP_BUNDLE";
export const START_BUNDLE = "START_BUNDLE";

export const SET_LOG_PREFERENCES = "SET_LOG_PREFERENCES";
export const SET_BUNDLE_PREFERENCES = "SET_BUNDLE_PREFERENCES";

export const SELECT_BUNDLE = "SELECT_BUNDLE";

export const DISMISS_BUNDLE = "DISMISS_BUNDLE";
