export const LOG_TYPES = {
  INFO: "LOG_INFO",
  ERROR: "LOG_ERROR",
  WARNING: "LOG_WARNING",
  DEBUG: "LOG_DEBUG",
  ALL: "ALL",
};

export const BUNDLE_STATES = {
  ACTIVE: "ACTIVE",
  RESOLVED: "RESOLVED",
  ALL: "ALL",
  UNINSTALLED: "UNINSTALLED",
  INSTALLED: "INSTALLED",
  STOPPING: "STOPPING",
  STARTING: "STARTING",
};
